// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("EvgTsvDotMe.PagesProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("EvgTsvDotMe.PagesProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing EvgTsvDotMe.PagesProvider."
  )>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EvgTsvDotMe.PagesProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "EvgTsvDotMe.PagesProvider"

    let [<Literal>] AssemblyDescription =
        "This library is for the .NET platform implementing EvgTsvDotMe.PagesProvider."

    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"