services:
  webapp:
    image: evgtsvdotme
    build:
      context: .
      dockerfile: EvgTsvDotMe/Dockerfile
    ports:
      - "8080:8080"
    read_only: true   
    security_opt:
      - "no-new-privileges=true"
