// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("EvgTsvDotMe.TypeProviders.DesignTime")>]
[<assembly: AssemblyProductAttribute("EvgTsvDotMe.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing EvgTsvDotMe.TypeProviders.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "EvgTsvDotMe.TypeProviders.DesignTime"

    [<Literal>]
    let AssemblyProduct = "EvgTsvDotMe.TypeProviders"

    [<Literal>]
    let AssemblyDescription =
        "This library is for the .NET platform implementing EvgTsvDotMe.TypeProviders."

    [<Literal>]
    let AssemblyVersion = "1.0.0"

    [<Literal>]
    let AssemblyFileVersion = "1.0.0"
