let title = """
# This file is auto-generated by Generaptor.""".Trim()

#r "nuget: Generaptor"
open Generaptor
open Generaptor.GitHubActions
open type Generaptor.GitHubActions.Commands

let fileName = "buildAndDeploy"
let scriptsDir = "./Scripts"

let scriptPath = $"{scriptsDir}/{fileName}.fsx"
let testEncodingScriptPath = $"{scriptsDir}/Test-Encoding.ps1"

let workflows = [
    let workflow name body = workflow name [
        header title
        yield! body
    ]
    
    let dotnetVersion = "10.0.x"

    let checkoutAction = Auto "actions/checkout"
    let dotnetSetupAction = Auto "actions/setup-dotnet"
    
    let setUpDotNetSdkStep = step(
        name = "Set up .NET SDK",
        usesSpec = dotnetSetupAction,
        options = Map.ofList [
            "dotnet-version", dotnetVersion
        ]
    )
    
    let checkoutStep = step(
        name = "Check out the sources",
        usesSpec = checkoutAction
    )
    
    let runBuild = step(
        name = "Run build script",
        shell = "pwsh",
        run = "./build.ps1"
    )
    
    let env = [
        setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"
        setEnv "DOTNET_NOLOGO" "1"
    ]
    
    workflow "main" [
        name "Build and Deploy"
        onPushTo "main"
        onPullRequestTo "main"
        onSchedule "0 0 * * 6"
        onWorkflowDispatch
        
        job "encoding" [
            runsOn "ubuntu-24.04"
            step(
                usesSpec = checkoutAction
            )
            step(
                name = "Verify encoding",
                shell = "pwsh",
                run = testEncodingScriptPath
            )
        ]
        
        job "verify-code-format" [
            runsOn "ubuntu-24.04"
            
            yield! env
            
            checkoutStep
            setUpDotNetSdkStep
            
            step(
                name = "Restore Fantomas",
                run = "dotnet tool restore"
            )
            step(
                name = "Verify code format",
                run = "dotnet fantomas --check ."
            )
        ]
        
        job "verify-workflows" [
            runsOn "ubuntu-24.04"

            yield! env
            
            checkoutStep
            setUpDotNetSdkStep

            step(
                name = "Verify generated CI definition",
                shell = "pwsh",
                run = $"dotnet fsi {scriptPath} verify"
            )
        ]
        
        job "build" [            
            runsOn "ubuntu-24.04"
            
            yield! env
            
            checkoutStep
            setUpDotNetSdkStep
            
            runBuild
            
            step(
                name = "Build Docker image",
                run = "docker build -f ./EvgTsvDotMe/Dockerfile -t evgtsvdotme:${{ github.sha }} -t evgtsvdotme:latest ./"
            )
            
            step(
                name = "Verify Docker image",
                run = "docker images | grep evgtsvdotme"
            )
            
            step(
                name = "Save Docker image",
                run = """
mkdir -p /tmp
docker save evgtsvdotme:latest -o /tmp/evgtsvdotme.tar
echo "Docker image saved successfully"
ls -lh /tmp/evgtsvdotme.tar
"""
            )
            
            step(
                name = "Upload Docker image artifact",
                usesSpec = Auto "actions/upload-artifact",
                options = Map.ofList [
                    "name", "docker-image"
                    "path", "/tmp/evgtsvdotme.tar"
                    "retention-days", "1"
                    "if-no-files-found", "error"
                ]
            )
        ]
        
        job "deploy" [
            runsOn "ubuntu-24.04"
            needs "build"
            
            yield! env
            
            step(
                name = "Download Docker image artifact",
                usesSpec = Auto "actions/download-artifact",
                options = Map.ofList [
                    "name", "docker-image"
                    "path", "/tmp"
                ]
            )
            
            step(
                name = "Transfer Docker image",
                usesSpec = ActionWithVersion "appleboy/scp-action@master",
                options = Map.ofList [
                    "host", "${{ secrets.SERVER_HOST }}"
                    "username", "${{ secrets.SERVER_USER }}"
                    "key", "${{ secrets.SERVER_SSH_KEY }}"
                    "source", "/tmp/evgtsvdotme.tar"
                    "target", "/tmp/"
                ]
            )
            
            step(
                name = "Load and run Docker image",
                usesSpec = ActionWithVersion "appleboy/ssh-action@master",
                options = Map.ofList [
                    "host", "${{ secrets.SERVER_HOST }}"
                    "username", "${{ secrets.SERVER_USER }}"
                    "key", "${{ secrets.SERVER_SSH_KEY }}"
                    "script", """
set -e
REPO_PATH="/home/${{ secrets.SERVER_USER }}/apps/evgtsvdotme"
DOCKER_IMAGE_PATH="/tmp/evgtsvdotme.tar"

echo "=== Checking Docker image ==="
if [ ! -f "$DOCKER_IMAGE_PATH" ]; then
    echo "Error: Docker image file not found at $DOCKER_IMAGE_PATH"
    echo "Available files in /tmp:"
    ls -la /tmp/ | head -20
    exit 1
fi

echo "=== Docker image info ==="
ls -lh "$DOCKER_IMAGE_PATH"

echo "=== Loading Docker image ==="
docker load -i "$DOCKER_IMAGE_PATH"

echo "=== Verifying loaded image ==="
docker images | grep evgtsvdotme || echo "Warning: Image not found in docker images output"

echo "=== Creating docker compose configuration ==="
cd "$REPO_PATH"
cat > docker-compose.yml << 'EOF'
services:
  webapp:
    image: evgtsvdotme
    build:
      context: .
      dockerfile: EvgTsvDotMe/Dockerfile
    ports:
      - "8080:8080"
    read_only: true   
    security_opt:
      - "no-new-privileges=true"
EOF

echo "=== Deploying with docker compose ==="
docker compose up -d

echo "=== Waiting for application to be ready ==="
sleep 5

echo "=== Checking application status ==="
docker compose ps

echo "=== Cleaning up ==="
rm -f "$DOCKER_IMAGE_PATH"

echo "=== Deployment completed successfully ==="
"""
                ]
            )
        ]
    ]
]

exit <| EntryPoint.Process fsi.CommandLineArgs workflows
