// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("EvgTsvDotMe.TypeProviders.Runtime")>]
[<assembly: AssemblyProductAttribute("EvgTsvDotMe.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing EvgTsvDotMe.TypeProviders."
  )>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EvgTsvDotMe.TypeProviders.Runtime"
    let [<Literal>] AssemblyProduct = "EvgTsvDotMe.TypeProviders"

    let [<Literal>] AssemblyDescription =
        "This library is for the .NET platform implementing EvgTsvDotMe.TypeProviders."

    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
